### ISSUE TITLE
Not all created playlists shown

### ISSUE THREAD

**Issue by slimdtrain** [danilowoz/coverify#20]
Only a portion of my user created playlists are shown on the page. I do have a lot of made playlists. Only 23 are shown but I have 37 in total.

**Comment by danilowoz** [comment]
Hey @slimdtrain thanks for sharing your issue, but it seems strange since the tool gets all 50 playlist that belongs to you. Here's important to notice that **playlists you follow or public playlist** will not appear in that list, as Spotify doesn't grant permission to edit such playlists.

Let me know if it helps you.

**Comment by danilowoz** [comment]
I'm going to close this issue, but please feel free to reopen it.
